BUCKET = "LRT_S3_BUCKET"

# config keys for okta
OKTA_DOMAIN = "OKTA_DOMAIN"
OKTA_API_KEY = "OKTA_API_KEY"

# config keys for log-ingestion
COMPANY_NAME = "COMPANY_NAME"
LM_ACCESS_ID = "LM_ACCESS_ID"
LM_ACCESS_KEY = "LM_ACCESS_KEY"
LM_BEARER_TOKEN = "LM_BEARER_TOKEN"
LM_RESOURCE_ID = "LM_RESOURCE_ID"
INCLUDE_METADATA_KEYS = "INCLUDE_METADATA_KEYS"
MAX_BACK_FILL_DURATION_MIN = "MAX_BACK_FILL_DURATION_MIN"
LM_SERVICE_NAME_KEY = "LM_SERVICE_NAME_KEY"

# constants
OKTA_KEY_MSG = "displayMessage"
OKTA_KEY_TIMESTAMP = "published"
LM_KEY_SERVICE = "resource.service.name"
MAX_ALLOWED_PAYLOAD_SIZE = 8 * 1024 * 1024
ENCODING = "utf-8"
LM_LOG_SOURCE = "okta"
LOG_INGESTION_RESOURCE_PATH = "/log/ingest"
