name: Python

on:
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Check out code 
      uses: actions/checkout@v2

    - name: Dockerfile build & test
      run: docker build -t lambda .
